Revert "mtd: ubi: wl: avoid erasing a PEB which is empty"
This reverts commit 32317ce22a8e23054830334689bdf6fa7f48c13d.

compilation error:
/drivers/mtd/ubi/wl.c: In function 'wear_leveling_worker':
/drivers/mtd/ubi/wl.c:1006: error: 'struct ubi_device' has no member named 'free_count'
/drivers/mtd/ubi/wl.c: At top level:
/drivers/mtd/ubi/wl.c:1064: error: conflicting types for 'ensure_wear_leveling'
/drivers/mtd/ubi/wl.c:756: note: previous declaration of 'ensure_wear_leveling' was here
make[6]: *** [drivers/mtd/ubi/wl.o] Error 1